export const allNavesQuery = `*[_type == "naveIndustrial"] | order(nave asc) {
  "id": naveId,
  nave,
  parque,
  ubicacion,
  superficieFt2,
  superficieM2,
  terreno,
  clearHeightFt,
  alturaMaxM,
  docks,
  docksDetalle,
  estacionamiento,
  patioManiobras,
  piso,
  techo,
  paredes,
  iluminacion,
  subestacion,
  hvac,
  sprinklers,
  estatus,
  nota,
  images,
  shortDescription,
  features,
  applications
}`
